# Generated by Django 2.2.15 on 2021-04-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='comments',
        ),
    ]
