# Generated by Django 3.2 on 2021-11-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211103_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
