# Generated by Django 3.2 on 2021-11-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211103_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
