# Generated by Django 3.2 on 2021-11-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_suggestion_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
