# Generated by Django 3.2 on 2021-11-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211103_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.batch'),
        ),
    ]
