# Generated by Django 3.2 on 2021-11-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_announcement_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='batch',
        ),
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.ManyToManyField(blank=True, null=True, to='base.Batch'),
        ),
    ]
