# Generated by Django 3.2 on 2021-11-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20211109_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='time_start',
        ),
        migrations.AddField(
            model_name='routine',
            name='time',
            field=models.CharField(choices=[('0', 'Sunday'), ('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday')], default='Sunday', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='Sunday', max_length=20),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.batch')),
                ('routine', models.ManyToManyField(blank=True, null=True, to='base.Routine')),
            ],
        ),
    ]
