# Generated by Django 3.2 on 2021-11-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211109_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.batch'),
        ),
    ]
