# Generated by Django 3.2 on 2021-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20211109_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='batch',
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
