# Generated by Django 3.2 on 2021-11-09 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20211109_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='batch',
            field=models.ManyToManyField(blank=True, to='base.Batch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.batch'),
        ),
    ]
