# Generated by Django 3.2 on 2021-11-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20211110_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
